### ISSUE TITLE
First name and Last name not displayed on registration preview and acknowledgement during update UIN process 

### ISSUE THREAD

**Issue by tisshadjac** [WuriGuinea/wuriguinea-registration#46]
![image](https://user-images.githubusercontent.com/64141579/91924565-ae334080-ec98-11ea-9de1-448358b0a6cc.png)

![image](https://user-images.githubusercontent.com/64141579/91924588-c014e380-ec98-11ea-84a8-336340ca41a7.png)

**Comment by hosurkrishnan** [comment]
This is fixed and tested

**Comment by wuritechteam** [comment]
@tisshadjac to test and fix it

**Comment by tisshadjac** [comment]
resolved
