### ISSUE TITLE
Unable to update address and parent information from preview page

### ISSUE THREAD

**Issue by jrosetf** [WuriGuinea/wuriguinea-registration#56]
1) Create a packet
2) In the preview page, click on the edit icon in the address and parent information section

Expected: User should be able to update the address and parent info

Actual: Nothing happens on clicking the edit icons.

![image](https://user-images.githubusercontent.com/45810590/92683874-b0109a00-f351-11ea-9a46-2c00527a5b5a.png)

**Comment by wuritechteam** [comment]
Bug fixed and merged on 1.1.1
